### PR TITLE
Fix links to isoDate and objectWithOnly matchers

### PR DESCRIPTION
**Pull request by srushti**
It looks like links need to be all lowercase.

Check `isoDate` and `objectWithOnly` at https://github.com/TabDigital/strummer/blob/master/MATCHERS.md right now.

### CODE REVIEW

**Comment by rprieto** [comment]
Good pickup :+1:

**Comment by srushti** [comment]
@rprieto The build's failing for a duplicate key in `.eslintrc` from 1b013a910d458cdc5dcdf2dfad5acb75fd8d934d. Not sure if it's only failing now. It's not like `eslint` has a wild card version and a newer version is more strict or anything. At any rate, if we can decide which rule we want I can fix it as part of this PR. Presumably, we want `strict: [2, "global"]` rather than `strict: false`.

**Comment by srushti** [comment]
It's now failing for coverage on `lib/strummer.js` because of the change I made because of `guard-for-in`. But those lines are still run as part of the test, so I'm not sure what's happening.



For now, I'll switch to the line where that rule was turned off since it didn't seem to hurting us so far.

**Comment by rprieto** [comment]
Very strange. I'm :+1: with removing the problematic lines.

**Comment by jaketracey** [comment]
@rprieto is this repo supposed to be public? I keep getting notifications from it o_O

**Comment by rprieto** [comment]
Hi! Yes it's a public open-source module. You can un-watch it at the top.

**Pull request merged**
