### PR TITLE
Make the time part optional in the isoDate matcher

### PR DESCRIPTION
**Pull request by srushti**
First attempt at solving at #23. I haven't included a timezone option yet. Assuming we're happy with how this looks, I'll do that too.

@TabDigital/ping-api

### CODE REVIEW

**Comment by mehdivk** [comment]
Unit tests are failed.

**Comment by mehdivk** [comment]
Also proposed regex for matching dates are not smart enough, they can validate things such as 0001-00-00 which is basically an invalid date.

**Comment by mehdivk** [comment]
I will work on Regex to see if I can come back with better Regex or not.

**Comment by srushti** [comment]
@mehdivk Sure, if you want. That's an unrelated issue though. Raise a separate issue for it, and fix it subsequently?

**Comment by nizhu** [comment]
can we not use moment or the native js date parser? date parsing cant be done with reasonable regex. feb 29th happens every 4 years. have fun!

**Comment by srushti** [comment]
And not exactly every four years either.

**Comment by nguyenchr** [comment]
if we are validating that it is a valid date I think we should be using `moment`

**Comment by nguyenchr** [comment]
similar to what we do in `api-service-account`

```coffee
s['YYYY-MM-DD'] = ->
  return s (value) ->
    if _.isArray value
      return 'should not have multiple values'
    if (typeof value != 'string')
      return 'should be a string'
    if not value.match /^\d{4}-\d{2}-\d{2}$/
      return "date should be in format YYYY-MM-DD"
    else if not moment(value, 'YYYY-MM-DD', true).isValid()
      return "date should be in format YYYY-MM-DD"
```

**Comment by rprieto** [comment]
:+1: to using moment. This was a *very* basic matcher, so if we're thinking of extending it to be smarter `moment` makes a lot of sense. Then maybe we should look at what moment offers in terms of formats, and maybe piggyback on that for the options we offer.

**Comment by srushti** [comment]
Can we merge this PR with the basic matcher though?

**Comment by srushti** [comment]
Hello? Is this thing on?

**Comment by rprieto** [comment]
:+1: from me

**Pull request merged**
