### PR TITLE
Updated Dependencies

### PR DESCRIPTION
**Pull request by mehdivk**
Dependencies (dev and normal) are all updated to latest stable versions.

### CODE REVIEW

**Comment by rprieto** [comment]
Out of curiosity, could you the results of the performance tests before/after the bump up?

**Comment by mehdivk** [comment]
@rprieto  Sure, this is before
```
Performance

┌───────────────────────┬─────────────────┐
│ Number of validations │ Total time (ms) │
├───────────────────────┼─────────────────┤
│ 100                   │ 3               │
├───────────────────────┼─────────────────┤
│ 1,000                 │ 11              │
├───────────────────────┼─────────────────┤
│ 10,000                │ 68              │
└───────────────────────┴─────────────────┘
```

And this is after:
```
Performance

┌───────────────────────┬─────────────────┐
│ Number of validations │ Total time (ms) │
├───────────────────────┼─────────────────┤
│ 100                   │ 3               │
├───────────────────────┼─────────────────┤
│ 1,000                 │ 11              │
├───────────────────────┼─────────────────┤
│ 10,000                │ 67              │
└───────────────────────┴─────────────────┘
```

**Comment by nguyenchr** [comment]
hell yeah `1ms` improvement :speedboat:

**Comment by rprieto** [comment]
:D
Looks great, thanks :+1:

**Pull request merged**
