### PR TITLE
Moving to a faster prototype-based version

### PR DESCRIPTION
**Pull request by rprieto**
:bulb: Idea: strummer based on prototypes to avoid functions being re-created all the time :bulb: 

- seems about `2x` as fast, based on `performance.spec.js`

| strummer version | iterations | time       |
|-------------------------|--------------|------------|
| v1 | 10,000 | 235ms
| v2 | 10,000 |  122ms

- haven't made any other tests pass yet

:sob: 

- changes the syntax slightly

```js
new s.object({name: 'string'})
```

- fixes inconsistencies 

```js
// with the old strummer
s({name: 'string'})(value) //ok
s.object({name: 'string'})(value) // not ok, you need to pass <path> as a first arg
s(s.object({name: 'string')) // ok

// with the new strummer, both work
new s.object({name: 'string'}).match(value)
new s.object({name: 'string'}).match(path, value)
```

### CODE REVIEW

**Comment by kiddkai** [comment]
I keep working on this now.

**Comment by kiddkai** [comment]
testing still failing, but all the matchers are switch to prototype based, including unit tests

**Comment by kiddkai** [comment]
Done, it will becomes a breaking change. And we need to changes the major version of it. I run the tests in my macbook air.

This is the `prototype` branch:

| Number of validations | Total time (ms) |
| ----------------------------- | -------------------- |
| 100                              | 38                     |
| 1,000                           | 129                   |
| 10,000                         | 938                   |

This is the `master` branch:

| Number of validations | Total time (ms) |
| ----------------------------- | -------------------- |
| 100                              |  21                    |
| 1,000                           | 120                   |
| 10,000                         | 1432                 |

**Comment by rprieto** [comment]
Nice one :+1: 

I can see 3 tests that might have disappeared (unless I missed them):
-  `it('matchers can return other matchers'`
-  `it('matchers can return other matchers (nested)'`
-  `it('can return dynamic matchers'`

Does `v2` still support that functionality? (might be something to be done in the base `Matcher` class)

**Comment by kiddkai** [comment]
I remove those tests since we all move to prototype way to do it. It's
doable to add that kind of functionality but it seems that we can use
something like createMatcher to create the actual class? Anyway it's good
for us to discuss about it before we merge to make sure everyone can work
with the new api.

**Comment by rprieto** [comment]
These tests are about specific functionality though, e.g. `a matcher can return another matcher`. We need to make sure `v2` still supports that (I can think of places where we use it), or explain other alternatives otherwise.

I'm not sure what `createMatcher` (or the current `factory` class) give us. The prototype definition is quite small, but if we want to save a few lines, maybe we can move to [babel.io](https://babeljs.io) & ES6 classes?

**Comment by kiddkai** [comment]
Yeah, but using the prototype way to doing this, we can using some kind of object composition to to that, like:

```js
var CustomMatcher = s.createMatcher({
  initialize: function() {
    this.subMatcher =  new s.number();
  },
  match: function(path, value) {
    return this.subMatcher.match(path, value);
  }
});
```

Anyway, we can make something like the previous functional, just few line changes of the compile function to adepts `a matcher can return anther matcher`, just want some actual example to see if it's make sense in this prototype version.

The `createMatcher` or `factory` is pretty simple now. Adding `babeljs` is a great idea. The reason why I didn't add it is because I am  not quite sure if we really needs the whole `babel` to supports the only `class` inherits syntax. But it's more fun to doing that way. For the other developers not using `babel` I think it may still necessary to adding some kind of `helper` to create a Matcher to hide the Matcher inherit in our side. Like some library:

```js
var CommentBox = React.createClass({
  render: function() {
    return (
    );
  }
});

**Comment by rprieto** [comment]
You're right your example would work. It's probably that it was a lot harder to do before in `v1`.. Let's have a chat with @nguyenchr to see if there's any other cases.

Otherwise the `Matcher::match` function could simply unwind any matchers in a loop, like it used to do before ([s.js line 38](https://github.com/TabDigital/strummer/blob/master/lib/s.js#L38)) - but if it's not necessary then even better :smile:

:+1: for the factory if it makes things simpler.

**Comment by nguyenchr** [comment]
I think the original reason we created `strummer` instead of using `js-match` was for the specific use case of `a matcher can return another matcher`

would we still be able to do the following in `v2`?

```coffee
betSchema = (path, bet) ->
  return s.object(bet) unless (bet? and typeof bet is 'object')
  switch bet.type
    when 'FIXED_ODDS' then exports.fixedOddsReq
    when 'PARIMUTUEL' then exports.parimutuelReq
    else exports.invalidBetReq
```

where `fixedOddsReq`, `parimutuelReq` and `invalidReq` are all matchers

**Comment by kiddkai** [comment]
Hi @nguyenchr 

Maybe we can do something like this ?

```coffee
betSchema = s.createMatcher
  initialize: ->
  match: (path, bet) ->
    return s.object(bet).match(path, bet) unless (bet? and typeof bet is 'object')
    matcher = null
    switch bet.type
      when 'FIXED_ODDS' then matcher = exports.fixedOddsReq
      when 'PARIMUTUEL' then matcher = exports.parimutuelReq
      else matcher = exports.invalidBetReq
    match(path, bet)
```

So at the same time we can still exports the JSONSchema of it.

```js
betSchema = s.createMatcher
  initialize: ->
  toJSONSchema: ->
    type: 'object'
    properties:  {} # auto generate..
  match: (path, bet) ->
    return s.object(bet).match(path, bet) unless (bet? and typeof bet is 'object')
    matcher = null
    switch bet.type
      when 'FIXED_ODDS' then matcher = exports.fixedOddsReq
      when 'PARIMUTUEL' then matcher = exports.parimutuelReq
      else matcher = exports.invalidBetReq
    match(path, bet)
```

**Comment by nguyenchr** [comment]
@kiddkai that looks good to me

**Comment by kiddkai** [comment]
@rprieto @nguyenchr Good to move to the next version?

**Comment by rprieto** [comment]
Looks good to me! Maybe 2 last things:

- should we be consistent and use `createMatcher(init, match)` everywhere (currently only 1/2 the built-in matchers use it?
- should we try and port 1 or 2 big projects to use `2.0.0` locally, and see if anything is missing, before publishing `v2`? Or maybe we can publish a first cut as `2.0.0-alpha`.

**Comment by kiddkai** [comment]
Good point, let me update the api first then move promotion to `2.0.0-alpha`.

**Comment by rprieto** [comment]
Alrighty, all rebased, and included @kiddkai's awesome performance fixes. The `README` example went from `200ms` to `85ms`.

Ready to :ship: , nice work everyone!

**Comment by kiddkai** [comment]
:rocket: :rocket: :rocket: :rocket:

**Comment by mehdivk** [comment]
:+1:

**Pull request merged**
